build:
  # meta information
  doc: "development build"
  name: "App Name"
  vstring: "1.2.0-keklol"
  # directory to take as root (all paths assumed relative to it, unless absolute)
  root: .
  # where to put the assembled build
  target:
    - build/dist/dev
    - build/dist/archive/1.2.0

include:
  # put specified file / CONTENTS of specified folder (key) into
  # destination folder (value); if file, filename is preserved
  src: "."
  changelog.txt: doc
#  doc/software/requirements.txt: doc
#  doc/software/visa_shell.md: eyp/hardware

exclude:
  # see shutil.copytree documentation
  patterns:
    - "*.pyc"
    - placeholder
    - "__pycache__"
    - "*.pyproject"
    - "*.pyproject.user"
    - "*.ui"
  # specific files to exclude from e.g. diretories specified in include
  specific:
    - "src/build.py"
    - "src/some_dir"

qt:
  # CLI command to use
  compiler: "pyside6-uic"
  # files to compile. For consistency, e.g. popup.ui --> popup_ui.py
  forms:
    - "src/eyp/gui/forms/popup.ui"
